import { useState, useEffect, useMemo } from "react";
import { c, panel, label, input, button, tag } from "./theme.js";
import { PROBES, loadContext, runProbe } from "./probes.js";

// The test bench.
//
// Pick a group, pick a probe, pick up to four models, run them against the
// operator's real portfolio, read the outputs side by side.
//
// Two properties this UI has to preserve, both of which are easy to lose:
//
//   1. It must be obvious what is being spent. Every run multiplies cost by the
//      number of models selected, and the image probe is roughly four cents a frame
//      per model. So the run button says how many calls it is about to make, and the
//      cap is four rather than "all of them".
//
//   2. It must be obvious what the output is being judged against. A model's answer
//      means nothing without the question, so the probe's blurb states what to look
//      for, and results carry latency and JSON-parse status rather than just prose.

const MAX_MODELS = 4;

// Capture is the cheapest group to run and the fastest to read, so it is the least
// costly place to land someone who is opening the bench to see what it does.
const INITIAL_GROUP = "capture";

/** Pretty-print whatever a probe returned, without pretending to understand it. */
function renderOutput(output) {
  if (output == null) return "(no output)";
  if (typeof output === "string") return output;
  try { return JSON.stringify(output, null, 2); } catch { return String(output); }
}

function ResultColumn({ result, catalogue }) {
  const model = catalogue.find((m) => m.id === result.model);
  const isImage = result.ok && result.output?.data && result.output?.mimeType;

  return (
    <div style={{ ...panel, flex: "1 1 300px", minWidth: 280, display: "flex", flexDirection: "column" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 8 }}>
        <div style={{ fontSize: 12.5, fontWeight: 700 }}>{model?.label || result.model}</div>
        <span style={tag(result.ok ? c.ok : c.bad)}>{result.ok ? `${result.ms}ms` : "failed"}</span>
      </div>

      {!result.ok ? (
        <div style={{ fontSize: 12, color: c.bad, lineHeight: 1.6, whiteSpace: "pre-wrap" }}>{result.error}</div>
      ) : isImage ? (
        <>
          <img
            src={`data:${result.output.mimeType};base64,${result.output.data}`}
            alt={`Generated by ${result.model}`}
            style={{ width: "100%", borderRadius: 3, border: `1px solid ${c.border}`, display: "block" }}
          />
          <div style={{ fontSize: 11, color: c.textMuted, marginTop: 8, lineHeight: 1.5 }}>
            {result.ms}ms · not saved anywhere — right-click to keep it
          </div>
        </>
      ) : (
        <pre style={{ margin: 0, fontSize: 11.5, color: c.textSub, lineHeight: 1.55, whiteSpace: "pre-wrap",
          wordBreak: "break-word", maxHeight: 420, overflowY: "auto" }}>
          {renderOutput(result.output)}
        </pre>
      )}
    </div>
  );
}

export function BenchPanel({ config }) {
  const [ctx, setCtx] = useState(null);
  const [ctxErr, setCtxErr] = useState("");
  const [group, setGroup] = useState(INITIAL_GROUP);
  const [probeId, setProbeId] = useState(PROBES[INITIAL_GROUP][0].id);
  // Seeded here as well as on group change, so the incumbent is already selected on
  // first paint rather than only after the operator switches groups once.
  const [selected, setSelected] = useState(
    () => (config.routing[INITIAL_GROUP] ? [config.routing[INITIAL_GROUP]] : [])
  );
  const [inputs, setInputs] = useState({});
  const [running, setRunning] = useState(false);
  const [results, setResults] = useState(null);

  useEffect(() => {
    loadContext().then(setCtx).catch((e) => setCtxErr(e.message || "Could not read the portfolio."));
  }, []);

  const groupsWithProbes = Object.keys(config.groups).filter((k) => (PROBES[k] || []).length > 0);
  const probes = PROBES[group] || [];

  // Changing the group invalidates the probe, the selection and any results, and
  // changing the probe invalidates its input defaults. Both are state derived from
  // another piece of state, so they reset during render rather than in an effect —
  // the same pattern GuideDrawer in App.jsx uses, and for the same two reasons: no
  // extra render, and no frame showing the previous group's probe.
  const [lastGroup, setLastGroup] = useState(group);
  if (lastGroup !== group) {
    setLastGroup(group);
    setProbeId(probes[0]?.id || "");
    setResults(null);
    // Seed the selection with whatever this group runs on now: the comparison an
    // operator wants is almost always the incumbent against a challenger.
    setSelected(config.routing[group] ? [config.routing[group]] : []);
  }

  const probe = probes.find((p) => p.id === probeId) || probes[0];

  const [lastProbeId, setLastProbeId] = useState(probe?.id);
  if (lastProbeId !== probe?.id) {
    setLastProbeId(probe?.id);
    setInputs({ ...(probe?.inputs || {}) });
  }

  // Eligible models for this group, filtered by the same capability rule the
  // registry and the server use.
  const eligible = useMemo(() => config.catalogue.filter((m) => {
    const g = config.groups[group];
    if (!g || m.modality !== g.modality) return false;
    return Object.entries(g.requires || {}).every(([cap, want]) => !want || m.caps?.[cap] === true);
  }), [config, group]);

  const toggle = (id) => setSelected((prev) =>
    prev.includes(id) ? prev.filter((x) => x !== id)
      : prev.length >= MAX_MODELS ? prev : [...prev, id]
  );

  const blocked = probe?.needs?.includes("items") && ctx?.isEmpty;

  const run = async () => {
    setRunning(true); setResults(null);
    // Parallel: these are independent calls and the whole value is seeing them
    // together. runProbe never rejects, so one model failing leaves the rest intact.
    const out = await Promise.all(selected.map((model) => runProbe({ probe, ctx, inputs, model })));
    setResults(out);
    setRunning(false);
  };

  if (ctxErr) return <div style={{ ...panel, borderColor: c.bad, color: c.bad, fontSize: 12 }}>{ctxErr}</div>;
  if (!ctx)   return <div style={{ fontSize: 12, color: c.textMuted }}>Reading your portfolio…</div>;

  return (
    <div>
      <div style={{ ...panel, marginBottom: 14 }}>
        <div style={{ fontSize: 12, color: c.textSub, lineHeight: 1.6 }}>
          Every probe calls the same function the app calls, with the same prompt and your real portfolio
          {ctx.isEmpty ? "" : ` (${ctx.items.length} initiatives)`} — only the model differs. Nothing here is
          saved to your portfolio.
        </div>
        {ctx.isEmpty && (
          <div style={{ fontSize: 12, color: c.warn, marginTop: 8, lineHeight: 1.6 }}>
            This browser has no initiatives stored, so probes that read the portfolio are unavailable. Open the app
            in this browser first — the console reads the same local data.
          </div>
        )}
      </div>

      {/* Group */}
      <div style={{ ...label, marginBottom: 6 }}>Feature group</div>
      <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 16 }}>
        {groupsWithProbes.map((k) => (
          <button key={k} onClick={() => setGroup(k)} style={button(group === k ? "primary" : "default")}>
            {config.groups[k].label}
          </button>
        ))}
      </div>
      {Object.keys(config.groups).some((k) => (PROBES[k] || []).length === 0) && (
        <div style={{ fontSize: 11.5, color: c.textMuted, marginTop: -10, marginBottom: 16, lineHeight: 1.5 }}>
          No bench for {Object.keys(config.groups).filter((k) => (PROBES[k] || []).length === 0)
            .map((k) => config.groups[k].label).join(", ")} — renders are asynchronous and priced per second, and
          Creative Studio already shows the per-script cost of each tier before spending anything. Routing still applies.
        </div>
      )}

      {/* Probe */}
      {probes.length > 1 && (
        <>
          <div style={{ ...label, marginBottom: 6 }}>Probe</div>
          <select style={{ ...input, cursor: "pointer", marginBottom: 10 }} value={probeId} onChange={(e) => setProbeId(e.target.value)}>
            {probes.map((p) => <option key={p.id} value={p.id}>{p.label}</option>)}
          </select>
        </>
      )}
      {probe && (
        <div style={{ fontSize: 12, color: c.textSub, lineHeight: 1.6, marginBottom: 6 }}>
          <strong style={{ color: c.text }}>What to look for:</strong> {probe.blurb}
        </div>
      )}
      {probe?.note && (
        <div style={{ fontSize: 11.5, color: c.textMuted, lineHeight: 1.5, marginBottom: 14 }}>{probe.note}</div>
      )}

      {/* Which initiative, for probes that read one */}
      {probe?.usesInitiative && !ctx.isEmpty && (
        <div style={{ marginTop: 10, marginBottom: 14 }}>
          <div style={{ ...label, marginBottom: 5 }}>Initiative</div>
          <select style={{ ...input, cursor: "pointer" }} value={inputs.initiativeId || ""}
            onChange={(e) => setInputs((p) => ({ ...p, initiativeId: e.target.value }))}>
            <option value="">Most recently closed (default)</option>
            {ctx.items.map((i) => (
              <option key={i.id} value={i.id}>{i.initId ? `${i.initId} — ` : ""}{i.title}</option>
            ))}
          </select>
        </div>
      )}

      {/* Free-text inputs */}
      {probe?.inputs && Object.keys(probe.inputs).map((key) => (
        <div key={key} style={{ marginBottom: 12 }}>
          <div style={{ ...label, marginBottom: 5 }}>{key}</div>
          <textarea
            style={{ ...input, minHeight: 54, resize: "vertical" }} value={inputs[key] ?? ""}
            onChange={(e) => setInputs((p) => ({ ...p, [key]: e.target.value }))}
          />
        </div>
      ))}

      {/* Models */}
      <div style={{ ...label, marginBottom: 6, marginTop: 16 }}>
        Models — up to {MAX_MODELS} ({selected.length} selected)
      </div>
      <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 8 }}>
        {eligible.map((m) => {
          const on = selected.includes(m.id);
          const atCap = !on && selected.length >= MAX_MODELS;
          const isCurrent = config.routing[group] === m.id;
          return (
            <button key={m.id} onClick={() => toggle(m.id)} disabled={atCap}
              title={atCap ? `Deselect one first — ${MAX_MODELS} is the cap` : m.blurb}
              style={{ ...button(on ? "primary" : "default"), opacity: atCap ? 0.4 : 1,
                cursor: atCap ? "not-allowed" : "pointer" }}>
              {m.label}{isCurrent ? " · live" : ""}{m.unverified ? " ?" : ""}
            </button>
          );
        })}
      </div>
      {/* An unconfirmed id fails as a 404 from the provider. Say so before the run
          rather than letting the result column be the first hint. */}
      {selected.some((id) => eligible.find((m) => m.id === id)?.unverified) && (
        <div style={{ fontSize: 11.5, color: c.warn, lineHeight: 1.5, marginBottom: 4 }}>
          Models marked <strong>?</strong> have an unconfirmed model id and may fail with a 404. Use
          “Verify id” on the Routing tab to check them against the provider.
        </div>
      )}

      <div style={{ display: "flex", gap: 10, alignItems: "center", marginTop: 14, flexWrap: "wrap" }}>
        <button
          style={{ ...button("primary"), opacity: running || !selected.length || blocked ? 0.45 : 1,
            cursor: running || !selected.length || blocked ? "default" : "pointer" }}
          disabled={running || !selected.length || blocked} onClick={run}
        >
          {running ? "Running…" : `Run ${selected.length} call${selected.length === 1 ? "" : "s"}`}
        </button>
        {blocked && (
          <span style={{ fontSize: 11.5, color: c.warn }}>This probe needs initiatives in the portfolio.</span>
        )}
        {group === "image" && selected.length > 0 && !blocked && (
          <span style={{ fontSize: 11.5, color: c.warn }}>
            Roughly {(selected.length * 4)}¢ — image generation is billed per frame, per model.
          </span>
        )}
      </div>

      {results && (
        <div style={{ marginTop: 22 }}>
          <div style={{ ...label, marginBottom: 8 }}>
            Results · {probe.label}
            {results.some((r) => !r.ok) ? " · some models failed, which is itself a result" : ""}
          </div>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "flex-start" }}>
            {results.map((r) => <ResultColumn key={r.model} result={r} catalogue={config.catalogue} />)}
          </div>
        </div>
      )}
    </div>
  );
}
